name: Build and Deploy to Docker Hub and AWS EC2
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build the JAR
        run: mvn package
      - name: Build the Docker image
        run: docker build -t bharatwajv/test:3.0.0 .
      - name: Log in to Docker Hub
        run: docker login -u bharatwajv -p ${{ secrets.DOCKER_TOKEN }}
      - name: Push the Docker image to Docker Hub
        run: docker push bharatwajv/test:3.0.0
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.HOSTNAME}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '         
              # Now we have got the access of EC2 and we will start the deploy .
              sudo chmod 666 /var/run/docker.sock &&
              docker ps --quiet | wc -l | grep -q "1" && docker stop $(docker ps --quiet) || echo "No containers running." &&
              docker pull bharatwajv/test:3.0.0 && 
              docker run -p 8080:8080 -d bharatwajv/test:3.0.0
              '